import React, { Component}  from 'react';
import DictEzApp from './dict-ez/DictEzApp.js';

/**
 * Default Application Main Component
 * <p>
 * This component is generated by "Create React App"
 */
class App extends Component {
  /**
   * React JS Render function
   */
  render() {
    return (
<DictEzApp></DictEzApp>
    );
  }
}

// Default exported component
export default App;
